on: [push]
name: build
jobs:
  runhaskell:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.6'
      - run: cabal build && cabal test
